### ISSUE TITLE
Unexpected character when building the solution

### ISSUE THREAD

**Issue by rokka** [NetCoreTemplates/selfhost#1]
Hello,

I have setup a new project:

C:\Devel>dotnet-new web webtest
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'.
Restoring packages for C:\Devel\webtest\webtest.Tests\webtest.Tests.csproj...
Restoring packages for C:\Devel\webtest\webtest.ServiceInterface\webtest.ServiceInterface.csproj...
Restoring packages for C:\Devel\webtest\webtest.ServiceModel\webtest.ServiceModel.csproj...
Restoring packages for C:\Devel\webtest\webtest\webtest.csproj...
  CACHE https://www.myget.org/F/servicestack/FindPackagesById()?id='ServiceStack.Interfaces'&semVerLevel=2.0.0
  CACHE https://www.myget.org/F/servicestack/FindPackagesById()?id='Microsoft.NET.Test.Sdk'&semVerLevel=2.0.0
  CACHE https://www.myget.org/F/servicestack/FindPackagesById()?id='NUnit'&semVerLevel=2.0.0
  CACHE https://www.myget.org/F/servicestack/FindPackagesById()?id='NUnit3TestAdapter'&semVerLevel=2.0.0
  CACHE https://api.nuget.org/v3-flatcontainer/servicestack/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.test.sdk/index.json
  CACHE https://www.myget.org/F/servicestack/FindPackagesById()?id='ServiceStack'&semVerLevel=2.0.0
  CACHE https://api.nuget.org/v3-flatcontainer/nunit3testadapter/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/servicestack.interfaces/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/nunit/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/servicestack.kestrel/index.json
  CACHE https://www.myget.org/F/servicestack/FindPackagesById()?id='ServiceStack.Kestrel'&semVerLevel=2.0.0
Committing restore...
Generating MSBuild file C:\Devel\webtest\webtest.ServiceModel\obj\webtest.ServiceModel.csproj.nuget.g.props.
Generating MSBuild file C:\Devel\webtest\webtest.ServiceModel\obj\webtest.ServiceModel.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Devel\webtest\webtest.ServiceModel\obj\project.assets.json
Restore completed in 822.74 ms for C:\Devel\webtest\webtest.ServiceModel\webtest.ServiceModel.csproj.
Committing restore...
Generating MSBuild file C:\Devel\webtest\webtest.ServiceInterface\obj\webtest.ServiceInterface.csproj.nuget.g.props.
Generating MSBuild file C:\Devel\webtest\webtest.ServiceInterface\obj\webtest.ServiceInterface.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Devel\webtest\webtest.ServiceInterface\obj\project.assets.json
Restore completed in 1.06 sec for C:\Devel\webtest\webtest.ServiceInterface\webtest.ServiceInterface.csproj.
Committing restore...
Generating MSBuild file C:\Devel\webtest\webtest.Tests\obj\webtest.Tests.csproj.nuget.g.props.
Generating MSBuild file C:\Devel\webtest\webtest.Tests\obj\webtest.Tests.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Devel\webtest\webtest.Tests\obj\project.assets.json
Restore completed in 1.08 sec for C:\Devel\webtest\webtest.Tests\webtest.Tests.csproj.
Committing restore...
Generating MSBuild file C:\Devel\webtest\webtest\obj\webtest.csproj.nuget.g.props.
Generating MSBuild file C:\Devel\webtest\webtest\obj\webtest.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Devel\webtest\webtest\obj\project.assets.json
Restore completed in 2.87 sec for C:\Devel\webtest\webtest\webtest.csproj.

NuGet Config files used:
    C:\Devel\webtest\NuGet.Config
    C:\Users\Andre\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
    https://www.myget.org/F/servicestack

But when I opne the solution and try to build it I get the following errors:

![image](https://user-images.githubusercontent.com/533290/54146350-16042480-4430-11e9-9608-e3fda5135d3b.png)

Can anyone help me?

**Comment by mythz** [comment]
Is this on Windows?

I'm able to create the template and run it without issue...

```
C:\src\wip>dotnet-new -v
Version: 1.0.7

C:\src\wip>dotnet-new web webtest

MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
Restoring packages for C:\src\wip\webtest\webtest.ServiceInterface\webtest.ServiceInterface.csproj...
Restoring packages for C:\src\wip\webtest\webtest.Tests\webtest.Tests.csproj...
Restoring packages for C:\src\wip\webtest\webtest\webtest.csproj...
Restoring packages for C:\src\wip\webtest\webtest.ServiceModel\webtest.ServiceModel.csproj...
...
Done Building Project "C:\src\wip\webtest\webtest.sln" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.38

C:\src\wip>cd webtest\webtest

C:\src\wip\webtest\webtest>dotnet run
Hosting environment: Development
Content root path: C:\src\wip\webtest\webtest
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
```

You can try updating `dotnet-new` to the latest version if you haven't already:

```
$ npm install -g @servicestack/cli@latest
```

Otherwise you can [install the selfhost](https://github.com/NetCoreTemplates/selfhost#selfhost) project template using the `web` .NET Tool instead:

```
$ dotnet tool install -g web

$ web new selfhost ProjectName
```

**Comment by rokka** [comment]
Hi.

I have found the problem. I am running VS on an german windows with english localization.

As soon as I build the solution on an english windows everything is working.


Greetings
Andre

**Comment by mythz** [comment]
Ahh good to know, thx for the update!
